apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.41.2
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.41.2
  releaseNotes: "kapp-controller 0.41.2 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:3bc7da1d0881125d0a2c3c9d0e1a70d5fa223bf9e2a539c2b812702812c07f7f
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
